tx:
  getMethodCall: |
    SELECT * FROM security.tx WHERE tx_id = $1
sync:
  deleteMethodProfiles: |
    DELETE FROM security.method_profile
  deleteMenuProfiles: |
    DELETE FROM security.menu_profile
  deleteMethods: |
    DELETE FROM security.method
  deleteMenus: |
    DELETE FROM security.menu
  deleteClasses: |
    DELETE FROM security.class
  deleteSubsystems: |
    DELETE FROM security.subsystem
  deleteTx: |
    DELETE FROM security.tx
  addSubsystemReturnId: |
    WITH ins AS (
      INSERT INTO security.subsystem (name)
      VALUES ($1)
      ON CONFLICT (name) DO NOTHING
      RETURNING subsystem_id
    )
    SELECT subsystem_id FROM ins
  addClassReturnId: |
    WITH ins AS (
      INSERT INTO security.class (subsystem_id, name)
      VALUES ($1, $2)
      ON CONFLICT (subsystem_id, name) DO NOTHING
      RETURNING class_id
    )
    SELECT class_id FROM ins
  addMethodReturnId: |
    WITH ins AS (
      INSERT INTO security.method (class_id, name)
      VALUES ($1, $2)
      ON CONFLICT (class_id, name) DO NOTHING
      RETURNING method_id
    )
    SELECT method_id FROM ins
  addMenuReturnId: |
    WITH ins AS (
      INSERT INTO security.menu (subsystem_id, name)
      VALUES ($1, $2)
      ON CONFLICT (subsystem_id, name) DO NOTHING
      RETURNING menu_id
    )
    SELECT menu_id FROM ins
  addTx: |
    INSERT INTO security.tx (tx_id, subsystem, class, method)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (subsystem, class, method) DO NOTHING
  getSubsystemId: |
    SELECT subsystem_id FROM security.subsystem WHERE name = $1
  getClassId: |
    SELECT c.class_id
    FROM security.class c
    JOIN security.subsystem s ON c.subsystem_id = s.subsystem_id
    WHERE s.name = $1 AND c.name = $2
  getMethodId: |
    SELECT method_id
    FROM security.method
    WHERE
      class_id = $1 AND
      name = $2
  getMenuId: |
    SELECT menu_id 
    FROM security.menu
    WHERE
      subsystem_id = $1 AND
      name = $2
  getProfileId: |
    SELECT profile_id FROM security.profile WHERE name = $1
  linkMethodProfile: |
    INSERT INTO security.method_profile (method_id, profile_id)
    VALUES ($1, $2)
    ON CONFLICT (method_id, profile_id) DO NOTHING 
  linkMenuProfile: |
    INSERT INTO security.menu_profile (menu_id, profile_id)
    VALUES ($1, $2)
    ON CONFLICT (menu_id, profile_id) DO NOTHING
user:
  getUserByEmail: |
    SELECT * FROM security.user WHERE email = $1
  getManyUsersByEmail: |
    SELECT user_id, email, "name", surname
    FROM security.user
    WHERE email = ANY($1)
  getUserById: |
    SELECT * FROM security.user WHERE user_id = $1
  getProfilesByUserId: |
    SELECT p.profile_id, p.name AS profile_name
    FROM security.user AS u
    JOIN security.user_profile AS up ON u.user_id = up.user_id
    JOIN security.profile AS p ON up.profile_id = p.profile_id
    WHERE u.user_id = $1
  getProfilesByEmail: |
    SELECT p.profile_id, p.name AS profile_name
    FROM security.user AS u
    JOIN security.user_profile AS up ON u.user_id = up.user_id
    JOIN security.profile AS p ON up.profile_id = p.profile_id
    WHERE u.email = $1
  getAllowedMenus: |
    SELECT DISTINCT m.name AS menu_name
    FROM security.user as u
    JOIN security.user_profile AS up ON u.user_id = up.user_id
    JOIN security.profile AS p ON up.profile_id = p.profile_id
    JOIN security.menu_profile AS mp ON p.profile_id = mp.profile_id
    JOIN security.menu AS m ON mp.menu_id = m.menu_id
    WHERE u.user_id = $1
  add: |
    INSERT INTO security.user (
      email, passwd, "name", surname
    )
    VALUES (
      $1, $2, $3, $4
    )
  changePassword: |
    UPDATE security.user
    SET passwd = $2
    WHERE email = $1
  addProfile: |
    INSERT INTO security.user_profile (user_id, profile_id)
    VALUES (
      (SELECT user_id FROM security.user WHERE email = $1),
      (SELECT profile_id FROM security.profile WHERE "name" = $2)
    );
  removeProfile: |
    DELETE FROM security.user_profile
    WHERE
      user_id = (SELECT user_id FROM security.user WHERE email = $1) AND
      profile_id = (SELECT profile_id FROM security.profile WHERE "name" = $2)
method:
  getAllowedProfiles: |
    SELECT p.profile_id, p.name AS profile_name
    FROM security.method AS m
    JOIN security.class AS c ON m.class_id = c.class_id
    JOIN security.subsystem AS s ON c.subsystem_id = s.subsystem_id
    JOIN security.method_profile AS mp ON m.method_id = mp.method_id
    JOIN security.profile AS p ON mp.profile_id = p.profile_id
    WHERE
      s.name = $1 AND
      c.name = $2 AND
      m.name = $3
  getProfileData: |
    SELECT
      s.name AS subsystem_name,
      c.name AS class_name,
      m.name AS method_name,
      p.name AS profile_name
    FROM security.method AS m
    JOIN security.class AS c ON m.class_id = c.class_id
    JOIN security.subsystem AS s ON c.subsystem_id = s.subsystem_id
    LEFT JOIN security.method_profile AS mp ON m.method_id = mp.method_id
    LEFT JOIN security.profile AS p ON mp.profile_id = p.profile_id
  addProfile: |
    INSERT INTO security.method_profile (method_id, profile_id)
    VALUES (
      (
        SELECT m.method_id
        FROM security.method AS m
        JOIN security.class AS c ON m.class_id = c.class_id
        JOIN security.subsystem s ON c.subsystem_id = s.subsystem_id
        WHERE s.name = $1
        AND c.name = $2
        AND m.name = $3
      ),
      (
        SELECT profile_id
        FROM security.profile
        WHERE name = $4
      )
    )
  removeProfile: |
    DELETE FROM security.method_profile
    WHERE profile_id = (
      SELECT profile_id FROM security.profile WHERE "name" = $4
    )
    AND method_id = (
      SELECT m.method_id
      FROM security.subsystem AS s
      JOIN security.class AS c ON s.subsystem_id = c.subsystem_id
      JOIN security.method AS m ON c.class_id = m.class_id
      WHERE
        s."name" = $1 AND
        c."name" = $2 AND
        m."name" = $3
    )
menu:
  getProfileData: |
    SELECT
      s.name AS subsystem_name,
      m.name AS menu_name,
      p.name AS profile_name
    FROM security.menu AS m
    JOIN security.subsystem AS s ON m.subsystem_id = s.subsystem_id 
    LEFT JOIN security.menu_profile AS mp ON m.menu_id = mp.menu_id
    LEFT JOIN security.profile AS p ON mp.profile_id = p.profile_id
  addProfile: |
    INSERT INTO security.menu_profile (menu_id, profile_id)
    VALUES (
      (
        SELECT menu_id
        FROM security.menu AS m
        JOIN security.subsystem AS s ON m.subsystem_id = s.subsystem_id
        WHERE
          s."name" = $1 AND
          m."name" = $2
      ),
      (
        SELECT profile_id
        FROM security.profile
        WHERE "name" = $3
      )
    )
  removeProfile: |
    DELETE FROM security.menu_profile
    WHERE profile_id = (
        SELECT profile_id
        FROM security.profile
        WHERE "name" = $3
    )
    AND menu_id = (
        SELECT m.menu_id
        FROM security.menu AS m
        JOIN security.subsystem AS s ON m.subsystem_id = s.subsystem_id
        WHERE
          s."name" = $1 AND
          m."name" = $2
    );
profile:
  getAll: |
    SELECT p.profile_id, p.name AS profile_name FROM security.profile AS p
  changeName: |
    UPDATE security.profile
    SET "name" = $2
    WHERE "name" = $1
  removeFromAllUsers: |
    DELETE FROM security.user_profile
    WHERE profile_id = (SELECT profile_id FROM security.profile WHERE "name" = $1)
  removeFromAllMethods: |
    DELETE FROM security.method_profile
    WHERE profile_id = (SELECT profile_id FROM security.profile WHERE "name" = $1)
  removeFromAllMenus: |
    DELETE FROM security.menu_profile
    WHERE profile_id = (SELECT profile_id FROM security.profile WHERE "name" = $1)
  delete: |
    DELETE FROM security.profile
    WHERE "name" = $1
event:
  create: |
    INSERT INTO events.event (
      name,
      start_dt,
      end_dt,
      desc_txt
    )
    VALUES ($1, $2, $3, $4)
  getAll: |
    SELECT * FROM events.event
  getEventById: |
    SELECT * from events.event
    WHERE event.event_id = $1
  update: |
    UPDATE events.event
    SET
      "name" = $2,
      desc_txt = $3,
      start_dt = $4,
      end_dt = $5
    WHERE
      event_id = $1
  getAttendances: |
    SELECT (user_id, attended) FROM people.attendee_event
    WHERE event_id = $1
location:
  create: |
    INSERT INTO events.location (country, city, "name")
    VALUES ($1, $2, $3)
    ON CONFLICT (country, city, "name") DO NOTHING
  getAll: |
    SELECT * FROM events.location
reservation:
  create: |
    INSERT INTO events.location_reservation (event_id, location_id, cost)
    VALUES ($1, $2, $3)
  getByEventId: |
    SELECT
      lr.cost,
      l.country,
      l.city,
      l."name" AS location_name
    FROM
      events.location_reservation AS lr
    JOIN 
      events.location AS l ON lr.location_id = l.location_id
    WHERE lr.event_id = $1
flyer:
  addEventFlyer: |
    INSERT INTO events.flyer (event_id, url)
    VALUES ($1, $2)
    ON CONFLICT (event_id)
      DO UPDATE SET
        url = EXCLUDED.url;
  getEventFlyer: |
    SELECT * FROM events.flyer
    WHERE event_id = $1
attendee:
  getAttendances: |
    SELECT td.event_id, ae.attended
    FROM people.attendee_event AS ae
    JOIN events.ticket AS t ON ae.ticket_id = t.ticket_id
    JOIN events.ticket_desc AS td ON t.ticket_desc_id = td.ticket_desc_id
    WHERE ae.user_id = $1;
  checkIn: |
    UPDATE people.attendee_event AS ae
    SET attended = TRUE
    FROM events.ticket AS t
    JOIN events.ticket_desc AS td ON t.ticket_desc_id = td.ticket_desc_id
    WHERE
      ae.ticket_id = t.ticket_id AND
      ae.user_id = $1 AND
      td.event_id = $2;
staff:
  add: |
    INSERT INTO people.staff (user_id, phone, "address")
    VALUES ($1, $2, $3)
  addToEvent: |
    INSERT INTO people.staff_event (staff_id, event_id, staff_role_id, cost_amt)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (staff_id, event_id, staff_role_id) DO NOTHING
  getAllInEvent: |
    SELECT
      se.staff_id,
      se.event_id,
      se.cost_amt AS cost,
      sr.staff_role_id,
      sr.name AS role_name,
      sr.desc_txt AS role_description
    FROM people.staff_event se
    JOIN people.staff_role sr ON se.staff_role_id = sr.staff_role_id
    WHERE se.event_id = $1;
  getRoles: |
    SELECT * FROM people.staff_role
  createRole: |
    INSERT INTO people.staff_role ("name", desc_txt)
    VALUES ($1, $2)
    ON CONFLICT ("name") DO NOTHING
costCategory:
  getAll: |
    SELECT cost_category_id, "name", desc_txt AS description
    FROM finance.cost_category
  add: |
    INSERT INTO finance.cost_category ("name", desc_txt)
    VALUES ($1, $2)
  update: |
    UPDATE finance.cost_category
    SET
      "name" = $2,
      desc_txt = $3
    WHERE
      cost_category_id = $1
paymentMethod:
  getAll: |
    SELECT payment_method_id, "name"
    FROM finance.payment_method
  add: |
    INSERT INTO finance.payment_method ("name")
    VALUES ($1)
payment:
  add: |
    INSERT INTO finance.payment (
      user_id,
      ticket_id,
      payment_method_id,
      amt
    )
    VALUES ($1, $2, $3, $4)
ticketDesc:
  add: |
    INSERT INTO events.ticket_desc (
      event_id,
      "name",
      desc_txt,
      cost
    )
    VALUES ($1, $2, $3, $4)
    RETURNING ticket_desc_id
  getByEventId: |
    SELECT
      td.ticket_desc_id,
      td.event_id,
      td.name,
      td.desc_txt AS description,
      td.cost,
      COUNT(t.ticket_id) AS available
    FROM events.ticket_desc td
    LEFT JOIN events.ticket t
      ON td.ticket_desc_id = t.ticket_desc_id
      AND t.user_id IS NULL
    WHERE td.event_id = $1
    GROUP BY 
      td.ticket_desc_id,
      td.event_id,
      td.name,
      td.desc_txt,
      td.cost
ticket:
  addMany: |
    INSERT INTO events.ticket (ticket_desc_id)
    SELECT $1
    FROM generate_series(1, $2)
  claimAvailable: |
    WITH claimed_ticket AS (
      UPDATE events.ticket
      SET user_id = $1
      WHERE ticket_id = (
        SELECT ticket_id
        FROM events.ticket
        WHERE
          ticket_desc_id = $2 AND
          user_id IS NULL
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      )
      RETURNING ticket_id
    )
    INSERT INTO people.attendee_event (user_id, ticket_id)
    SELECT $1, ticket_id
    FROM claimed_ticket
    ON CONFLICT (user_id, ticket_id) DO NOTHING
    RETURNING ticket_id
  verifyPaid: |
    SELECT
      CASE 
        WHEN COALESCE(SUM(p.amt), 0) >= td.cost THEN TRUE 
        ELSE FALSE
      END AS paid,
      ABS(COALESCE(SUM(p.amt), 0) - td.cost) AS difference
    FROM events.ticket t
    JOIN events.ticket_desc td ON t.ticket_desc_id = td.ticket_desc_id
    LEFT JOIN finance.payment p ON t.ticket_id = p.ticket_id
    WHERE t.ticket_id = $1
    GROUP BY t.ticket_id, td.cost